server.port=9390
#logging.level.root=TRACE
#logging.level.org.springframework.web=TRACE

# Spring Batch - use H2 in-memory DB for job metadata only
spring.datasource.url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
